services:
  - type: web
    name: resume-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: TELEGRAM_BOT_TOKEN
        sync: false
